### ISSUE TITLE
Codec Mismatch

### ISSUE THREAD

**Issue by softmanmaker** [silverhawke249/pyKSH-exporter#1]
I was using this tool to convert a ksh file and the name of the song contains Japanese letters. When exporting xml file, the program raised an error:

*Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\pyKSH-exporter-1.4-hotfix.1\main.pyw", line 869, in export_xml
    self.song_chart_data.write_xml(f)
  File "C:\Users\Administrator\Desktop\pyKSH-exporter-1.4-hotfix.1\sdvxparser\parser\ksh.py", line 651, in write_xml
    f.write(
UnicodeEncodeError: 'gbk' codec can't encode character '\uff7d' in position 122: illegal multibyte sequence*

As bemani uses shift-jis codec for music_db.xml, I think it would be better to use shift-jis when exporting xml files.

Also, though this is not a bug, I think it's better to generate a png of size 128\*128 and named jk_[song_id]_[difficluty_level]_t.png when exporting jackets. Bemani actually packed these 128\*128 pngs into an ifs file, without which the game will crash when playing the songs. Though it's easy to resize the png manually, I believe it would be more convenient if it is done by the program.

**Comment by silverhawke249** [comment]
okay, so when encoding isn't specified it defaults to system encoding -- it's utf-8 in my side so that doesn't cause issues, but gbk in yours. however, shift-jis is also limiting in output (there are many characters not available in shift-jis), so i think what i will do is to output to utf-8, but emit a warning if characters that don't exist in shift-jis are detected.

i will add the the 128*128 resized png into the list of generated images when you export the jacket.

**Comment by silverhawke249** [comment]
`UnicodeEncodeError` codec issue is fixed in 7cb0de6167a11ed21d025df62867e700f6fd8641.
Generating 128x128 PNG is added in 121c197d67a5c88ba481d2b6ad3cdc0a7f086090.
